from pathlib import Path
root=Path(__file__).resolve().parent

# Step 11: strengthen NO_SUITABLE_EXISTING_PAGE negative-proof rule.
p=root/'STEP_11_PAGE_OWNERSHIP_METHOD.md'
s=p.read_text(encoding='utf-8')
needle='`NO_SUITABLE_EXISTING_PAGE` means only:\n\n> plausible current pages were reviewed and none truthfully owns the full frozen user task.\n'
rep='''`NO_SUITABLE_EXISTING_PAGE` means only:\n\n> plausible current pages were reviewed and none truthfully owns the full frozen user task.\n\nBecause this is a **negative current-site existence claim**, it must also satisfy `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`: absence from the Step-1 inventory is not proof. Use current multi-route discovery (broad Codex/browser discovery when needed, plus targeted current first-party reads) and record coverage limitations. If current-site absence is not sufficiently proven, use an explicit unresolved/absence-not-proven state rather than a confident no-page verdict.\n'''
if 'Because this is a **negative current-site existence claim**' not in s:
    s=s.replace(needle,rep)
needle2='### 6.2 Refresh the current public-site page inventory\n\nUse current public-site evidence (Codex/ChatGPT public browsing/first-party reads as allowed by the job) to identify plausible owner candidates.\n'
rep2='''### 6.2 Refresh the current public-site page inventory\n\nUse `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`. Use current public-site evidence (Codex/ChatGPT public browsing/first-party reads as allowed by the job) to identify plausible owner candidates. A small named positive check can be done with targeted web reads; a material negative claim that no page exists on a large site requires broad multi-route discovery and should use Codex/browser as the preferred discovery channel when available.\n'''
s=s.replace(needle2,rep2)
p.write_text(s,encoding='utf-8')

# Step rules index: register universal freshness gate and Step-12 reopened state.
p=root/'STEP_RULES_INDEX.md'
s=p.read_text(encoding='utf-8')
needle='Canonical rules:\n\n```text\nROADMAP_STAGE_EXISTS != METHODOLOGY_VALIDATED\nRESEARCH_COLLECTED != METHOD_VALIDATED\n```\n'
rep='''Canonical rules:\n\n```text\nROADMAP_STAGE_EXISTS != METHODOLOGY_VALIDATED\nRESEARCH_COLLECTED != METHOD_VALIDATED\nOLD_SITE_INVENTORY != CURRENT_SITE_TRUTH\n```\n\nCurrent-site freshness authority for Steps 1, 11, 12, 13, 14 and 20:\n\n`CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`\n'''
if 'CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md' not in s:
    s=s.replace(needle,rep)
s=s.replace('| Step 1 | Existing-site discovery / business-page model | **APPROVED / ACTIVE** | `STEP_METHOD_REVIEW_AND_LESSONS_LEDGER.md` — one discovery pass is not automatically complete; cross-check channels and preserve evidence strength. |', '| Step 1 | Existing-site discovery / business-page model | **APPROVED / ACTIVE** | `STEP_METHOD_REVIEW_AND_LESSONS_LEDGER.md` + `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md` — one discovery pass is not automatically complete; cross-check channels, timestamp the inventory and preserve that it is a baseline snapshot rather than timeless absence proof. |')
s=s.replace('| **Step 11** | **Page ownership / keyword-to-page mapping** | **APPROVED / ACTIVE AFTER EXTERNAL METHOD AUDIT + PHRASE-LEVEL CORRECTION** | **`STEP_11_PAGE_OWNERSHIP_METHOD.md`** — cluster→owner is necessary but not sufficient; inspect member phrases, persist every Bridge/Codex acquisition immediately to GitHub with readback before the next interaction, distinguish target URL from proven Yandex relevant URL, and materialize/QA every active phrase→effective cluster→target URL/state row. |', '| **Step 11** | **Page ownership / keyword-to-page mapping** | **APPROVED / ACTIVE AFTER EXTERNAL METHOD AUDIT + PHRASE-LEVEL CORRECTION** | **`STEP_11_PAGE_OWNERSHIP_METHOD.md` + `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`** — refresh current candidate pages; a `NO_SUITABLE_EXISTING_PAGE` negative claim requires current multi-route absence evidence, not old-inventory absence. |')
s=s.replace('| **Step 12** | **Structural actions (keep/expand/split/merge/create)** | **APPROVED / ACTIVE AFTER EXTERNAL METHOD AUDIT + FAIL-CLOSED CORRECTIONS + INDEPENDENT QA** | **`STEP_12_STRUCTURAL_ACTION_METHOD.md`** — explicit coherent structural units; evidence-backed new-page boundaries; reviewed primary targets for implementable actions; evidence-derived confidence/maturity with current-state reasons; concrete hierarchy; full phrase→action map; deterministic Step-13 pair universe; independent QA with explicit evidence origin and evidence-valid SPLIT/MERGE controls. |', '| **Step 12** | **Structural actions (keep/expand/split/merge/create)** | **REOPENED / SECOND METHOD CORRECTION IN PROGRESS** | **`STEP_12_STRUCTURAL_ACTION_METHOD.md` + `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`** — current-site recheck immediately before CREATE, existing-content reuse audit, owner-goal/business-potential gate, then evidence-derived action/confidence and independent QA. D12-16..D12-20 are open until current-job revalidation completes. |')
s=s.replace('| Step 13 | Cannibalization diagnosis | **UNVALIDATED** | Must distinguish real competing-page conflict from normal multi-URL visibility. |', '| Step 13 | Cannibalization diagnosis | **UNVALIDATED** | Must distinguish real competing-page conflict from normal multi-URL visibility; before diagnosing a pair, re-read both current URLs under `CURRENT_SITE_FRESHNESS_AND_EXISTENCE_GATE.md`. |')
s=s.replace('| Step 14 | Search-only architecture freeze | **UNVALIDATED** | Must define what evidence is sufficient to freeze classic Search architecture before AI evidence. |', '| Step 14 | Search-only architecture freeze | **UNVALIDATED** | Must define what evidence is sufficient to freeze classic Search architecture before AI evidence and recheck implementation-critical current URLs before freeze. |')
s=s.replace('| Step 20 | Final QA | **UNVALIDATED** | Must reconcile claims, counts, evidence, URLs/actions and unresolved items against the promised Kwork output. |', '| Step 20 | Final QA | **UNVALIDATED** | Must reconcile claims, counts, evidence, URLs/actions and unresolved items against the promised Kwork output, including a lightweight current-URL/current-role recheck for implementation-critical pages. |')
s=s.replace('KW001_STEP12_METHOD_APPROVED_AFTER_INDEPENDENT_QA = true', 'KW001_STEP12_METHOD_REOPENED_AFTER_OWNER_BUSINESS_GOAL_AND_FRESHNESS_CHALLENGE = true')
p.write_text(s,encoding='utf-8')
print('CURRENT_SITE_FRESHNESS_REFERENCES_PATCHED')
