// B15 development qualification on the EXACT B14 package, not independent acceptance.
// Launcher/ownership/measurement derived from saved B14. Controlled DOM; no live upload.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(pathToFileURL(path.resolve(process.env.YMB_PPTR_HOME,'package.json')));
const puppeteer=require('puppeteer');
const root=fs.realpathSync(process.env.YMB_BROWSER_CANDIDATE),out=path.resolve(process.env.YMB_BROWSER_EVIDENCE);
fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const target='f591b39a381993c44284561236b9c5a278761db3d6b04059c59974e037c33f47';
const CID='99999999-8888-4777-8666-555555555555',KEY='https://chatgpt.com|'+CID,PAGE_URL='https://chatgpt.com/c/'+CID;
const fixture=fs.readFileSync(new URL('./b15_fixture.html',import.meta.url),'utf8');
const emit=v=>{const s=JSON.stringify({...v,time:new Date().toISOString()})+'\n';fs.appendFileSync(path.join(out,'browser.jsonl'),s);process.stdout.write(s);};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,ms=15000){const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await delay(100);}throw new Error(label);}
function tree(){const rows=[];function walk(d){for(const x of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,x.name);assert.equal(x.isSymbolicLink(),false);if(x.isDirectory())walk(f);else{assert.ok(x.isFile());rows.push([path.relative(root,f).split(path.sep).join('/'),hash(fs.readFileSync(f))]);}}}walk(root);rows.sort((a,b)=>a[0]<b[0]?-1:1);assert.equal(rows.length,67);return hash(Buffer.from(rows.map(([p,h])=>h+'  '+p+'\n').join('')));}
assert.equal(tree(),target);
let browser,w,wTarget,page,pid,monitor,deadline,stage='launch',peak=0,resourceStop=false,failed=0,tabId,extensionId;
const observedPids=new Set();const errors=[];
function memory(){if(!pid)return null;const rows=execFileSync('ps',['-eo','pid=,ppid=,rss='],{encoding:'utf8',timeout:1500}).trim().split('\n').map(l=>l.trim().split(/\s+/).map(Number));const owned=new Set([pid]);let changed=true;while(changed){changed=false;for(const [p,pp]of rows)if(owned.has(pp)&&!owned.has(p)){owned.add(p);changed=true;}}const selected=rows.filter(r=>owned.has(r[0]));for(const row of selected)observedPids.add(row[0]);const rss=selected.reduce((s,r)=>s+r[2],0);peak=Math.max(peak,rss);return{rss_kib:rss,pids:selected.map(r=>r[0])};}
async function diagnostics(){let dom=null,state=null;try{dom=await page.evaluate(()=>({fixture:__fixture,status:document.getElementById('ymb-file-delivery-status')?.textContent,body:document.body.innerText.slice(-3000)}));}catch{}try{state=await w.evaluate(async key=>{const e=await getConversationOutbox(key);return{outbox:e?{id:e.delivery_id,phase:e.phase,mode:e.delivery_mode}:null,operations:(await chrome.storage.local.get('wsmb_manual_operations')).wsmb_manual_operations?.[key],messages:globalThis.__b15_messages};},KEY);}catch{}return{dom,state};}
async function runCase(name,fn){stage=name;const t=Date.now();try{const details=await fn();emit({case:name,status:'PASS',...details,duration_ms:Date.now()-t,memory:memory()});return true;}catch(e){failed++;emit({case:name,status:resourceStop?'FAIL_RESOURCE':'FAIL_QUALIFICATION',error:String(e.stack||e),details:await diagnostics(),release_allowed:false});return false;}}
async function getWorker(exclude=null){wTarget=await browser.waitForTarget(t=>t!==exclude&&t.type()==='service_worker'&&t.url().startsWith('chrome-extension://')&&t.url().endsWith('/phase3_service_worker_bootstrap.js'),{timeout:20000});w=await wTarget.worker();assert.ok(w);extensionId=wTarget.url().split('/')[2];w.on('error',e=>errors.push(String(e)));return w;}
async function instrument(){await w.evaluate(()=>{globalThis.__b15_network=0;globalThis.fetch=async()=>{__b15_network++;throw new Error('B15_NO_PROVIDER_NETWORK');};globalThis.__b15_messages={};const old=handleMessage;handleMessage=async(m,s)=>{const k=String(m?.type||'');__b15_messages[k]=(__b15_messages[k]||0)+1;return old(m,s);};});}
async function outbox(){return w.evaluate(async key=>{const e=await getConversationOutbox(key);return e?{id:e.delivery_id,phase:e.phase,mode:e.delivery_mode}:null;},KEY);}
async function stageFile(mib,label){return w.evaluate(async({mib,label,key,tabId})=>{const d='b15-'+label;const ak='artifact-'+d;const descriptor=await YMBFileArtifactStore.stageTextArtifact({artifactKey:ak,deliveryId:d,filename:d+'.txt',text:'x'.repeat(mib*1024*1024)});const m=(await chrome.storage.local.get('wsmb_manual_operations')).wsmb_manual_operations||{};m[key]={operation_id:d,delivery_id:d,status:'delivering',conversation_key:key,tab_id:tabId,active_service:'search',request_executed:false};await chrome.storage.local.set({wsmb_manual_operations:m});await putOutbox(key,{delivery_id:d,operation_id:d,type:'manual',tab_id:tabId,phase:'claimed',report_text:'B15 file '+label,delivery_mode:'attachment_v2',artifact_descriptors:[descriptor],provider_executions:0});return{key:ak,id:d,size:descriptor.byte_length,chunks:descriptor.chunk_count};},{mib,label,key:KEY,tabId});}
async function artifactGone(key){return w.evaluate(async key=>{const A=YMBFileArtifactStore;const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});const db=await req(indexedDB.open(A.DB_NAME,A.DB_VERSION));const remaining=await req(db.transaction('chunks','readonly').objectStore('chunks').index('artifact_key').count(IDBKeyRange.only(key)));db.close();return{remaining,meta:!!await A.getMeta(key)};},key);}
async function fx(){return page.evaluate(()=>({sends:__fixture.sends,inputs:__fixture.inputs,changes:__fixture.changes,copy:__fixture.copy,errors:__fixture.errors,text:document.getElementById('prompt-textarea').value}));}
async function messageCounts(){return w.evaluate(()=>({...__b15_messages}));}
async function resetDelivery(){await w.evaluate(async key=>{await clearOutbox(key);const d=await chrome.storage.local.get('wsmb_manual_operations');const m=d.wsmb_manual_operations||{};delete m[key];await chrome.storage.local.set({wsmb_manual_operations:m});},KEY);await page.evaluate(()=>{__fixture.previewDelay=0;__fixture.files=[];document.getElementById('prompt-textarea').value='';document.getElementById('previews').replaceChildren();document.getElementById('upload-files').value='';__fixture.arm();});}
try{
 browser=await puppeteer.launch({headless:false,pipe:true,enableExtensions:[root],protocolTimeout:120000,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--host-resolver-rules=MAP * ~NOTFOUND',`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
 pid=browser.process()?.pid;assert.ok(pid);
 deadline=setTimeout(()=>{resourceStop=true;void browser.close();},330000);
 monitor=setInterval(()=>{try{const m=memory();fs.appendFileSync(path.join(out,'rss.jsonl'),JSON.stringify({stage,...m})+'\n');if(m.rss_kib>2097152){resourceStop=true;void browser.close();}}catch{}},250);
 await getWorker();await instrument();
 emit({case:'unchanged_package_owned_browser',status:'PASS',chrome:await browser.version(),puppeteer:require('puppeteer/package.json').version,tree:tree(),emergency_rss_mib:2048,scope:'Full process-tree RSS; watchdog is safety bound, not proof of leak freedom'});
 page=await browser.newPage();await page.setRequestInterception(true);page.on('request',r=>{if(r.isNavigationRequest()&&r.url()===PAGE_URL)void r.respond({status:200,contentType:'text/html; charset=utf-8',body:fixture});else void r.abort();});page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(PAGE_URL,{waitUntil:'domcontentloaded',timeout:20000});
 await until(async()=>w.evaluate(async url=>{const tab=(await chrome.tabs.query({})).find(t=>t.url===url);if(!tab)return false;return new Promise(ok=>chrome.tabs.sendMessage(tab.id,{type:'WS_GET_IDENTITY'},r=>{void chrome.runtime.lastError;ok(r?.ok===true);}));},PAGE_URL),'CONTENT_NOT_READY');
 tabId=await w.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,PAGE_URL);
 await w.evaluate(async({key,cid,tabId})=>{await chrome.storage.local.set({wsmb_conversation_bindings:{[key]:{binding_id:'b15',revision:1,origin:'https://chatgpt.com',conversation_id:cid,conversation_key:key}},wsmb_manual_modes:{[key]:true},ymb_service_contexts:{[key]:{active_service:'search'}},wsmb_auto_send:true,ymb_settings_schema_version:5});await YMBCredentialRuntime.save('search',{api_key:'QA_NOT_REAL_B15',folder_id:'qa-only',check_state:'PRESENT'});await new Promise(ok=>chrome.tabs.sendMessage(tabId,{type:'WS_APPLY_MANUAL_MODE',conversation_key:key,enabled:true,active_service:'search'},ok));},{key:KEY,cid:CID,tabId});
 const domReady=await runCase('real_content_native_copy_and_one_local_command',async()=>{
  await page.evaluate(()=>__fixture.append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'start',jobId:'b15-dom-job',queries:['fixture'],confirmBillable:true,maxRequests:1,maxCostRub:1})));
  const actions=()=>page.evaluate(()=>[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('button')]:[]).filter(b=>b.textContent.includes('Яндекс')).map(b=>({disabled:b.disabled,text:b.textContent})));
  await until(async()=>(await actions()).some(a=>!a.disabled),'YANDEX_CONTROL_NOT_READY');
  await page.click('button[aria-label="Copy"]');await delay(250);assert.equal((await messageCounts()).WS_EXECUTE_MANUAL_BLOCK||0,0);
  await page.evaluate(()=>{const b=[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('button')]:[]).find(b=>b.textContent.includes('Яндекс')&&!b.disabled);b.click();b.click();});
  await until(async()=>(await fx()).sends.length===1,'LOCAL_RESULT_NOT_SENT');await until(async()=>!(await outbox()),'LOCAL_RESULT_NOT_CONFIRMED');
  const s=await fx(),c=await messageCounts();assert.equal(c.WS_EXECUTE_MANUAL_BLOCK,1);assert.equal(s.copy,1);assert.match(s.sends[0].text,/SEARCH_ASYNC_BATCH_RESULT_V1/);assert.equal(c.WS_MANUAL_DELIVERY_COMPLETE,1);
  return{manual_messages:1,send_clicks:1,native_copy:1,local_action:true};
 });
 if(!domReady)await resetDelivery();
 for(const [cycle,mib]of [1,10,32,64,64,64].entries()){
  const ok=await runCase('full_file_delivery_'+mib+'MiB_'+(cycle+1),async()=>{
   await resetDelivery();const before=await fx(),count=await messageCounts(),mem=memory();const d=await stageFile(mib,'cycle-'+cycle);
   await until(async()=>(await fx()).sends.length===before.sends.length+1,'FILE_NOT_SENT',60000);await until(async()=>!(await outbox()),'FILE_NOT_ACKED');
   const after=await fx(),c=await messageCounts();assert.equal(after.changes-before.changes,1);assert.equal(after.inputs-before.inputs,1);assert.equal(after.sends.length-before.sends.length,1);
   const f=after.sends.at(-1).files;assert.equal(f.length,1);assert.equal(f[0].bytes,mib*1024*1024);assert.equal(f[0].size,f[0].bytes);assert.equal(f[0].allX,true);assert.deepEqual(after.errors,[]);
   assert.equal((c.WS_GET_OUTBOX_ARTIFACT_CHUNK||0)-(count.WS_GET_OUTBOX_ARTIFACT_CHUNK||0),d.chunks);assert.equal((c.WS_MANUAL_DELIVERY_COMPLETE||0)-(count.WS_MANUAL_DELIVERY_COMPLETE||0),1);assert.deepEqual(await artifactGone(d.key),{remaining:0,meta:false});
   await delay(500);return{mib,chunk_messages:d.chunks,one_DataTransfer_change:true,bytes_scanned_in_File_stream:f[0].bytes,send_clicks:1,cleanup:true,before:mem,after:memory(),live_upload:false};
  });if(!ok){await resetDelivery();break;}
 }
 await runCase('occupied_composer_preserved_then_manual_send',async()=>{
  await resetDelivery();await w.evaluate(()=>chrome.storage.local.set({wsmb_auto_send:false}));await page.evaluate(()=>{document.getElementById('prompt-textarea').value='USER_TEXT_KEEP';});const before=await fx();const d=await stageFile(1,'occupied');await delay(1800);assert.equal((await fx()).text,'USER_TEXT_KEEP');assert.equal((await fx()).changes,before.changes);assert.equal((await outbox()).phase,'claimed');
  await page.evaluate(()=>{document.getElementById('prompt-textarea').value='';document.getElementById('prompt-textarea').dispatchEvent(new Event('input',{bubbles:true}));});await until(async()=>(await outbox())?.phase==='attachment_ready','MANUAL_ATTACHMENT_NOT_READY');await delay(1200);assert.equal((await fx()).sends.length,before.sends.length);await page.click('#composer-submit-button');await until(async()=>!(await outbox()),'MANUAL_ATTACHMENT_NOT_CONFIRMED');assert.equal((await fx()).sends.length,before.sends.length+1);assert.deepEqual(await artifactGone(d.key),{remaining:0,meta:false});await w.evaluate(()=>chrome.storage.local.set({wsmb_auto_send:true}));return{user_text_preserved:true,automatic_send_while_disabled:0,manual_send:1};
 });
 // Actual worker termination uses official WebWorker.close(), not a substituted ID.
 await runCase('actual_worker_termination_saved_state_and_watch_only_delivery',async()=>{
  await resetDelivery();await w.evaluate(()=>chrome.storage.local.set({wsmb_auto_send:false}));const d=await stageFile(1,'restart');await until(async()=>(await outbox())?.phase==='attachment_ready','PRE_RESTART_FILE_NOT_READY');await delay(1000);const before=await fx();
  const oldSession=await w.evaluate(async()=>{const S=YMBSearchAsyncStore;await S.createJob({jobId:'b15-interrupted',owner:'b15',queries:['saved','unknown'],parameters:{region:'225'},folderId:'qa',maxRequests:2,maxCostMicrorub:200,unitCostMicrorub:100,now:1});await S.claim({jobId:'b15-interrupted',owner:'b15',workerId:WORKER_SESSION_ID,attemptId:'a',kind:'submit',now:1});await S.finishSubmit({jobId:'b15-interrupted',owner:'b15',index:0,attemptId:'a',outcome:'received',operationId:'fixture-op',rawText:'PRESERVED_RAW',now:2});await S.claim({jobId:'b15-interrupted',owner:'b15',workerId:WORKER_SESSION_ID,attemptId:'b',kind:'submit',now:2});return WORKER_SESSION_ID;});
  const oldTarget=wTarget;await w.close();await getWorker(oldTarget);await instrument();const newSession=await w.evaluate(()=>WORKER_SESSION_ID);assert.notEqual(oldSession,newSession);
  const r=await w.evaluate(async()=>{const S=YMBSearchAsyncStore;await S.recover({jobId:'b15-interrupted',owner:'b15',workerId:WORKER_SESSION_ID,now:3});return{summary:await S.getSummary('b15-interrupted','b15'),raw:(await S.readResult('b15-interrupted','b15',0)).raw_text,blocked:await S.claim({jobId:'b15-interrupted',owner:'b15',workerId:WORKER_SESSION_ID,attemptId:'c',kind:'submit',now:3})};});assert.equal(r.summary.counts.UNKNOWN,1);assert.equal(r.raw,'PRESERVED_RAW');assert.equal(r.blocked.allowed,false);
  await delay(1200);assert.equal((await fx()).changes,before.changes);assert.equal((await fx()).sends.length,before.sends.length);await page.click('#composer-submit-button');await until(async()=>!(await outbox()),'RESTART_DELIVERY_NOT_CONFIRMED');assert.deepEqual(await artifactGone(d.key),{remaining:0,meta:false});await w.evaluate(()=>chrome.storage.local.set({wsmb_auto_send:true}));return{old_session:oldSession,new_session:newSession,real_target_closed:true,raw_preserved:true,no_reattachment:true,unknown_blocks_submit:true};
 });
 // Store is real IndexedDB; provider results are deliberately synthetic, not Search calls.
 for(const n of [10,100,500,1500])await runCase('real_IDB_full_item_lifecycle_'+n,async()=>{
  const r=await w.evaluate(async n=>{const S=YMBSearchAsyncStore,j='b15-scale-'+n,o='b15-scale';let reads=0,writes=0,maxJob=0;const get=IDBObjectStore.prototype.get,put=IDBObjectStore.prototype.put,add=IDBObjectStore.prototype.add,all=IDBObjectStore.prototype.getAll,idx=IDBIndex.prototype.get;IDBObjectStore.prototype.get=function(...a){reads++;return get.apply(this,a);};IDBIndex.prototype.get=function(...a){reads++;return idx.apply(this,a);};function write(f,v,...a){writes++;if(this.name==='jobs')maxJob=Math.max(maxJob,JSON.stringify(v).length);return f.call(this,v,...a);}IDBObjectStore.prototype.put=function(...a){return write.call(this,put,...a);};IDBObjectStore.prototype.add=function(...a){return write.call(this,add,...a);};IDBObjectStore.prototype.getAll=function(){throw new Error('B15_WHOLE_STORE_READ_FORBIDDEN');};
   const t=performance.now();try{await S.createJob({jobId:j,owner:o,queries:Array.from({length:n},(_,i)=>'fixture-'+i),parameters:{region:'225'},folderId:'qa',maxRequests:n,maxCostMicrorub:n*100,unitCostMicrorub:100,now:1});for(let i=0;i<n;i++){const a='s-'+i,c=await S.claim({jobId:j,owner:o,workerId:WORKER_SESSION_ID,attemptId:a,kind:'submit',now:2});if(!c.allowed||c.item.index!==i)throw new Error('CLAIM_ID');await S.finishSubmit({jobId:j,owner:o,index:i,attemptId:a,outcome:'accepted',operationId:j+'-'+i,nextPollAt:3,now:2});}const submitted=performance.now();for(let i=0;i<n;i++){const a='c-'+i,c=await S.claim({jobId:j,owner:o,workerId:WORKER_SESSION_ID,attemptId:a,kind:'collect',now:3});if(!c.allowed||c.item.index!==i)throw new Error('COLLECT_ID');await S.finishCollect({jobId:j,owner:o,index:i,attemptId:a,outcome:'received',rawText:'raw-'+i,now:3});await S.finishNormalization({jobId:j,owner:o,index:i,normalized:{results:[{rank:1,url:'https://example.test/'+i}]},now:4});}let seen=0,after=-1;for(;;){const p=await S.pageItems(j,o,{after,limit:100});if(!p.rows.length)break;for(const row of p.rows){if(row.index!==seen++||row.state!=='SUCCEEDED')throw new Error('RECONCILIATION');}after=p.next_after;}return{n,seen,summary:await S.getSummary(j,o),reads,writes,max_job_characters:maxJob,submit_ms:Math.round(submitted-t),total_ms:Math.round(performance.now()-t)};}finally{IDBObjectStore.prototype.get=get;IDBObjectStore.prototype.put=put;IDBObjectStore.prototype.add=add;IDBObjectStore.prototype.getAll=all;IDBIndex.prototype.get=idx;}
  },n);assert.equal(r.seen,n);assert.equal(r.summary.counts.SUCCEEDED,n);assert.equal(r.summary.all_successful,true);assert.ok(r.reads<=30*n+100);assert.ok(r.writes<=20*n+100);assert.ok(r.max_job_characters<4096);return{...r,provider_results:'synthetic; real store and transactions'};
 });
 assert.equal(tree(),target);emit({case:'candidate_identity_after_campaign',status:'PASS',tree:target,errors,failed,release_allowed:false});
}catch(e){failed++;emit({case:stage,status:'FAIL_QUALIFICATION',error:String(e.stack||e),details:await diagnostics(),release_allowed:false});}
finally{clearInterval(monitor);clearTimeout(deadline);if(browser)try{await browser.close();}catch{}let remaining=[];for(const p of observedPids)try{const s=fs.readFileSync('/proc/'+p+'/stat','utf8');if(s.slice(s.lastIndexOf(')')+2).split(' ')[0]!=='Z')remaining.push(p);}catch{}emit({case:'owned_browser_cleanup',status:remaining.length?'FAIL':'PASS',remaining,peak_owned_rss_kib:peak,resource_stop:resourceStop,failed,independent_gate:false,release_allowed:false});if(remaining.length||failed||resourceStop)process.exitCode=1;}
