// B19 real-Chrome development qualification on exact 0.1.6 bytes.
// Controlled ChatGPT DOM and provider responses only. No live Yandex calls or owner profile.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(pathToFileURL(path.resolve(process.env.YMB_PPTR_HOME,'package.json')));
const puppeteer=require('puppeteer');
const root=fs.realpathSync(process.env.YMB_BROWSER_CANDIDATE),out=path.resolve(process.env.YMB_BROWSER_EVIDENCE);
const fixture=fs.readFileSync(process.env.YMB_CHATGPT_FIXTURE,'utf8');fs.mkdirSync(out,{recursive:true});
const TARGET='b87246c1377cda57cb9135f92814ec6885a1b607a9539be3a27bbc2fb1918b86';
const CID='61616161-7272-4838-8949-505050505050',KEY='https://chatgpt.com|'+CID,PAGE_URL='https://chatgpt.com/c/'+CID;
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const delay=ms=>new Promise(r=>setTimeout(r,ms));
const emit=v=>{const s=JSON.stringify({...v,time:new Date().toISOString()})+'\n';fs.appendFileSync(path.join(out,'browser.jsonl'),s);process.stdout.write(s);};
async function until(fn,label,ms=15000){const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await delay(100);}throw new Error(label);}
function tree(){const rows=[];function walk(d){for(const x of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,x.name);assert.equal(x.isSymbolicLink(),false);if(x.isDirectory())walk(f);else{assert.ok(x.isFile());rows.push([path.relative(root,f).split(path.sep).join('/'),hash(fs.readFileSync(f))]);}}}walk(root);rows.sort((a,b)=>a[0]<b[0]?-1:1);assert.equal(rows.length,67);return hash(Buffer.from(rows.map(([p,h])=>h+'  '+p+'\n').join('')));}
assert.equal(tree(),TARGET);
let browser,w,wTarget,page,pid,monitor,deadline,peak=0,failed=0,stage='launch',tabId;const pids=new Set(),errors=[];
function memory(){if(!pid)return null;const raw=execFileSync('ps',['-eo','pid=,ppid=,rss='],{encoding:'utf8',timeout:1500}).trim();const rows=raw?raw.split('\n').map(l=>l.trim().split(/\s+/).map(Number)):[];const owned=new Set([pid]);let change=true;while(change){change=false;for(const [p,pp] of rows)if(owned.has(pp)&&!owned.has(p)){owned.add(p);change=true;}}const selected=rows.filter(r=>owned.has(r[0]));for(const r of selected)pids.add(r[0]);const rss=selected.reduce((s,r)=>s+r[2],0);peak=Math.max(peak,rss);return{rss_kib:rss,pids:selected.map(r=>r[0])};}
async function getWorker(exclude=null){wTarget=await browser.waitForTarget(t=>t!==exclude&&t.type()==='service_worker'&&t.url().startsWith('chrome-extension://')&&t.url().endsWith('/phase3_service_worker_bootstrap.js'),{timeout:20000});w=await wTarget.worker();assert.ok(w);return w;}
async function diagnostics(){
 let worker=null,dom=null;
 try{worker=await w.evaluate(async key=>{const data=await chrome.storage.local.get(['wsmb_manual_operations','wsmb_outbox','wsmb_manual_modes','ymb_service_contexts','wsmb_auto_send']);let summary=null,item=null;try{summary=await YMBSearchAsyncStore.getSummary('b19-browser-job',key);}catch(e){summary={error:e?.code||String(e)}}try{item=(await YMBSearchAsyncStore.pageItems('b19-browser-job',key,{after:-1,limit:5})).rows;}catch(e){item={error:e?.code||String(e)}}return{hits:(globalThis.__b19_hits||[]).slice(),mode:globalThis.__b19_mode,integration:{ready:YMBSearchAsyncWorkerIntegration?.ready,providerEnabled:YMBSearchAsyncWorkerIntegration?.providerEnabled},auto_send:data.wsmb_auto_send,manual:data.wsmb_manual_operations?.[key]||null,outbox:data.wsmb_outbox?.[key]||null,manual_mode:data.wsmb_manual_modes?.[key],service:data.ymb_service_contexts?.[key],summary,item};},KEY);}catch(e){worker={diagnostic_error:String(e)}}
 try{dom=await page.evaluate(()=>({sends:__fixture.sends.map(x=>({text:String(x.text||'').slice(0,1500),files:x.files?.length||0})),changes:__fixture.changes,inputs:__fixture.inputs,status:[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('.ymb-status')]:[]).map(e=>e.textContent),actions:[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('button')]:[]).map(b=>({disabled:b.disabled,text:b.textContent})),composer:document.getElementById('prompt-textarea')?.value||'',fixture_controls:document.getElementById('controls')?.textContent||''}));}catch(e){dom={diagnostic_error:String(e)}}
 return{worker,dom,page_errors:errors.slice(),memory:memory()};
}
async function run(name,fn){stage=name;try{const v=await fn();emit({case:name,status:'PASS',...v,memory:memory()});return true;}catch(e){failed++;emit({case:name,status:'FAIL_QUALIFICATION',error:String(e.stack||e),diagnostics:await diagnostics(),release_allowed:false});return false;}}
async function actions(){return page.evaluate(()=>[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('button')]:[]).filter(b=>b.textContent.includes('Яндекс')).map(b=>({disabled:b.disabled,text:b.textContent})));}
async function append(text){await page.evaluate(t=>{if(!document.querySelector('#controls button[data-testid="send-button"]'))__fixture.arm();__fixture.append(t);},text);await until(async()=>(await actions()).some(x=>!x.disabled),'YANDEX_ACTION_NOT_READY');}
async function appendWithoutEnabledWait(text){await page.evaluate(t=>{if(!document.querySelector('#controls button[data-testid="send-button"]'))__fixture.arm();__fixture.append(t);},text);await until(async()=>(await actions()).length>0,'YANDEX_ACTION_ABSENT');}
async function click(){await page.evaluate(()=>{const b=[...document.querySelectorAll('*')].flatMap(e=>e.shadowRoot?[...e.shadowRoot.querySelectorAll('button')]:[]).find(b=>b.textContent.includes('Яндекс')&&!b.disabled);if(!b)throw new Error('NO_ACTION');b.click();});}
async function waitsends(n){await until(()=>page.evaluate(n=>__fixture.sends.length===n,n),'REPORT_NOT_SENT',20000);}
async function clearTurn(){await page.evaluate(()=>{document.getElementById('conversation-root').replaceChildren();});await delay(300);}
async function outbox(){return w.evaluate(async key=>{const e=await getConversationOutbox(key);return e?{id:e.delivery_id,phase:e.phase}:null;},KEY);}
try{
 browser=await puppeteer.launch({headless:false,pipe:true,enableExtensions:true,protocolTimeout:120000,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--host-resolver-rules=MAP * ~NOTFOUND',`--disable-extensions-except=${root}`,`--load-extension=${root}`]});pid=browser.process()?.pid;assert.ok(pid);deadline=setTimeout(()=>void browser.close(),180000);monitor=setInterval(()=>{try{const m=memory();fs.appendFileSync(path.join(out,'rss.jsonl'),JSON.stringify({stage,...m})+'\n');if(m.rss_kib>2097152)void browser.close();}catch{}},250);
 await getWorker();
 emit({case:'exact_0_1_6_installed',status:'PASS',chrome:await browser.version(),puppeteer:require('puppeteer/package.json').version,tree:tree(),version:await w.evaluate(()=>chrome.runtime.getManifest().version),host:await w.evaluate(()=>chrome.runtime.getManifest().host_permissions),provider_enabled:await w.evaluate(()=>YMBSearchAsyncWorkerIntegration.providerEnabled),startup_fetches:0});
 assert.equal(await w.evaluate(()=>chrome.runtime.getManifest().version),'0.1.6');assert.equal(await w.evaluate(()=>YMBSearchAsyncWorkerIntegration.providerEnabled),true);
 page=await browser.newPage();await page.setRequestInterception(true);page.on('request',r=>{if(r.isNavigationRequest()&&r.url()===PAGE_URL)void r.respond({status:200,contentType:'text/html; charset=utf-8',body:fixture});else void r.abort();});page.on('pageerror',e=>errors.push(String(e)));await page.goto(PAGE_URL,{waitUntil:'domcontentloaded'});
 await until(async()=>w.evaluate(async url=>{const t=(await chrome.tabs.query({})).find(x=>x.url===url);if(!t)return false;return new Promise(ok=>chrome.tabs.sendMessage(t.id,{type:'WS_GET_IDENTITY'},r=>{void chrome.runtime.lastError;ok(r?.ok===true);}));},PAGE_URL),'CONTENT_NOT_READY');tabId=await w.evaluate(async url=>(await chrome.tabs.query({})).find(x=>x.url===url).id,PAGE_URL);
 await w.evaluate(async({key,cid,tabId})=>{await chrome.storage.local.set({wsmb_conversation_bindings:{[key]:{binding_id:'b19',revision:1,origin:'https://chatgpt.com',conversation_id:cid,conversation_key:key}},wsmb_manual_modes:{[key]:true},ymb_service_contexts:{[key]:{active_service:'search'}},wsmb_auto_send:true,ymb_settings_schema_version:5});await YMBCredentialRuntime.save('search',{api_key:'B19_SYNTHETIC_SEARCH_KEY',folder_id:'qa-folder',check_state:'PRESENT'});await new Promise(ok=>chrome.tabs.sendMessage(tabId,{type:'WS_APPLY_MANUAL_MODE',conversation_key:key,enabled:true,active_service:'search'},ok));},{key:KEY,cid:CID,tabId});
 await w.evaluate(()=>{globalThis.__b19_hits=[];globalThis.__b19_mode='normal';globalThis.fetch=async(url,init)=>{const u=String(url);__b19_hits.push({url:u,method:init?.method||'GET',authorization:init?.headers?.Authorization||null,body:init?.body?JSON.parse(init.body):null});if(__b19_mode==='unknown')throw new Error('B19_CONTROLLED_UNKNOWN');if(u==='https://searchapi.api.cloud.yandex.net/v2/web/searchAsync'){const body=JSON.parse(init.body);return new Response(JSON.stringify({id:'b19-op-'+body.query.queryText.replace(/[^a-z0-9]/gi,'').slice(0,12),done:false}),{status:200,headers:{'content-type':'application/json'}});}if(u.startsWith('https://operation.api.cloud.yandex.net/operations/')){const id=u.split('/').pop();const xml='<yandexsearch><response><found priority="all">1</found><results><grouping><group><doc><url>https://example.test/b19</url><domain>example.test</domain><title>B19 result</title></doc></group></grouping></results></response></yandexsearch>';return new Response(JSON.stringify({id,done:true,response:{rawData:btoa(xml)}}),{status:200,headers:{'content-type':'application/json'}});}throw new Error('UNEXPECTED_PROVIDER_URL '+u);};const rebuilt=YMBSearchAsyncWorkerTransport.autoInstall();if(!rebuilt?.ready||rebuilt.providerEnabled!==true)throw new Error('B19_ASYNC_REINSTALL_FAILED');globalThis.YMBSearchAsyncWorkerIntegration=rebuilt;});
 let sends=0;
 await run('manual_start_zero_network',async()=>{await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'start',jobId:'b19-browser-job',queries:['browserfixture'],confirmBillable:true,maxRequests:1,maxCostRub:1}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'START_NOT_ACKED');const hits=await w.evaluate(()=>__b19_hits.slice());assert.equal(hits.length,0);await clearTurn();return{provider_calls:0};});
 const submitPassed=await run('manual_submit_exact_searchAsync_POST',async()=>{await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'submitN',jobId:'b19-browser-job',count:1}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'SUBMIT_NOT_ACKED');const hits=await w.evaluate(()=>__b19_hits.slice());assert.equal(hits.length,1);assert.equal(hits[0].url,'https://searchapi.api.cloud.yandex.net/v2/web/searchAsync');assert.equal(hits[0].method,'POST');assert.equal(hits[0].authorization,'Api-Key B19_SYNTHETIC_SEARCH_KEY');assert.equal(hits[0].body.folderId,'qa-folder');const summary=await w.evaluate(async key=>YMBSearchAsyncStore.getSummary('b19-browser-job',key),KEY);assert.equal(summary.counts.WAITING,1);await clearTurn();return{provider_calls:1,operation_waiting:1,fixture_send_rearmed:true};});
 if(!submitPassed){emit({case:'network_diagnostic_stop_after_submit_failure',status:'PASS',diagnostics:await diagnostics(),note:'Later cases intentionally not executed because they depend on a completed submit delivery. Product not modified.',release_allowed:false});}
 if(submitPassed){
  await run('manual_collect_exact_operation_GET_and_normalize',async()=>{await w.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open(YMBSearchAsyncStore.DB_NAME,YMBSearchAsyncStore.DB_VERSION);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});await new Promise((ok,no)=>{const tx=db.transaction('items','readwrite');const s=tx.objectStore('items');const r=s.get(['b19-browser-job',0]);r.onsuccess=()=>{const v=r.result;v.next_poll_at=0;s.put(v)};tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});db.close();});await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'collect',jobId:'b19-browser-job'}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'COLLECT_NOT_ACKED');const hits=await w.evaluate(()=>__b19_hits.slice());assert.equal(hits.length,2);assert.ok(hits[1].url.startsWith('https://operation.api.cloud.yandex.net/operations/b19-op-'));assert.equal(hits[1].method,'GET');assert.equal(hits[1].authorization,'Api-Key B19_SYNTHETIC_SEARCH_KEY');const result=await w.evaluate(async key=>YMBSearchAsyncStore.readResult('b19-browser-job',key,0),KEY);assert.equal(result.normalized.results[0].url,'https://example.test/b19');await clearTurn();return{provider_calls:2,normalized:true};});
  await run('command_injection_cannot_override_provider_origin_or_credential',async()=>{const before=await w.evaluate(()=>__b19_hits.length);await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'start',jobId:'inject-job',queries:['safe'],confirmBillable:true,maxRequests:1,maxCostRub:1,url:'https://evil.invalid',api_key:'EVIL',folderId:'evil'}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'INJECT_NOT_ACKED');assert.equal(await w.evaluate(()=>__b19_hits.length),before);const last=await page.evaluate(()=>__fixture.sends.at(-1).text);assert.match(last,/YMB_ERROR_V1/);assert.ok(!last.includes('B19_SYNTHETIC_SEARCH_KEY'));await clearTurn();return{provider_calls:0,fail_closed:true};});
 }
 await run('manual_disabled_blocks_before_network',async()=>{const before=await w.evaluate(()=>__b19_hits.length);await w.evaluate(key=>chrome.storage.local.set({wsmb_manual_modes:{[key]:false}}),KEY);await page.evaluate(()=>document.getElementById('conversation-root').replaceChildren());await appendWithoutEnabledWait('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'status',jobId:'b19-browser-job'}));assert.ok((await actions()).every(x=>x.disabled));assert.equal(await w.evaluate(()=>__b19_hits.length),before);await w.evaluate(async({key,tabId})=>{await chrome.storage.local.set({wsmb_manual_modes:{[key]:true}});await new Promise(ok=>chrome.tabs.sendMessage(tabId,{type:'WS_APPLY_MANUAL_MODE',conversation_key:key,enabled:true,active_service:'search'},ok));},{key:KEY,tabId});await clearTurn();return{provider_calls:0,disabled_controls:true};});
 if(submitPassed){await run('unknown_submit_never_auto_retries',async()=>{await w.evaluate(()=>{__b19_mode='unknown'});await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'start',jobId:'unknown-job',queries:['unknownfixture'],confirmBillable:true,maxRequests:1,maxCostRub:1}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'UNKNOWN_START_ACK');await clearTurn();const before=await w.evaluate(()=>__b19_hits.length);await append('SEARCH_ASYNC_BATCH_API_V1\n'+JSON.stringify({action:'submit',jobId:'unknown-job'}));await click();await waitsends(++sends);await until(async()=>!(await outbox()),'UNKNOWN_SUBMIT_ACK');await delay(1500);const after=await w.evaluate(()=>__b19_hits.length);assert.equal(after,before+1);const sum=await w.evaluate(async key=>YMBSearchAsyncStore.getSummary('unknown-job',key),KEY);assert.equal(sum.counts.UNKNOWN,1);await w.evaluate(()=>{__b19_mode='normal'});await clearTurn();return{provider_calls_delta:1,unknown:1,no_auto_retry:true};});}
 assert.equal(tree(),TARGET);emit({case:'b19_network_campaign_identity',status:'PASS',tree:TARGET,errors,failed,release_allowed:false});
}catch(e){failed++;emit({case:stage,status:'FAIL_QUALIFICATION',error:String(e.stack||e),diagnostics:await diagnostics(),release_allowed:false});}finally{clearInterval(monitor);clearTimeout(deadline);if(browser)try{await browser.close();}catch{}const remain=[];for(const p of pids)try{const s=fs.readFileSync('/proc/'+p+'/stat','utf8');if(s.slice(s.lastIndexOf(')')+2).split(' ')[0]!=='Z')remain.push(p)}catch{}emit({case:'owned_browser_cleanup',status:remain.length?'FAIL':'PASS',remaining:remain,peak_owned_rss_kib:peak,failed,release_allowed:false});if(remain.length||failed)process.exitCode=1;}
