import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as fake from './idb_test_double.mjs';
const ctx=vm.createContext({...fake,TextEncoder});ctx.globalThis=ctx;vm.runInContext(fs.readFileSync(new URL('../candidate/shared/search_async_store.js',import.meta.url),'utf8'),ctx);const S=ctx.YMBSearchAsyncStore;
const owner='owner-test';let seq=0;
async function create(n=2,budget=n*100){const j='edge-'+(++seq);await S.createJob({jobId:j,owner,queries:Array.from({length:n},(_,i)=>'q'+i),parameters:{region:'225'},folderId:'folder',maxRequests:n,maxCostMicrorub:budget,unitCostMicrorub:100,now:1000});return j;}
const claim=(j,token,index)=>S.claim({jobId:j,owner,attemptId:token,workerId:'worker',kind:'submit',expectedIndex:index,now:1000});
const finish=(j,token,index,outcome,extra={})=>S.finishSubmit({jobId:j,owner,attemptId:token,index,outcome,now:1000,...extra});
const result=(id)=>({operationId:id,rawText:JSON.stringify({id,done:true,response:{rawData:'eA=='}})});
test('B3 edge: duplicate immediate settlement does not overwrite preserved response',async()=>{const j=await create();await claim(j,'a',0);await finish(j,'a',0,'received',result(j+'-op'));const before=await S.readResult(j,owner,0);const r=await finish(j,'a',0,'received',{...result(j+'-other'),rawText:'other'});assert.equal(r.duplicate,true);assert.deepEqual(await S.readResult(j,owner,0),before);assert.equal((await S.getSummary(j,owner)).operations_accepted,1);});
test('B3 edge: operation collision rolls back new raw and all acceptance counters',async()=>{const j=await create();await claim(j,'a',0);await finish(j,'a',0,'received',result(j+'-op'));await claim(j,'b',1);await assert.rejects(()=>finish(j,'b',1,'received',result(j+'-op')));assert.equal(await S.readResult(j,owner,1),undefined);assert.equal((await S.readItem(j,owner,1)).state,'SUBMITTING');assert.equal((await S.getSummary(j,owner)).operations_accepted,1);});
test('B3 edge: duplicate not-sent settlement cannot credit the budget twice',async()=>{const j=await create();await claim(j,'a',0);await finish(j,'a',0,'not_sent');await finish(j,'a',0,'not_sent');const p=await S.getSummary(j,owner);assert.equal(p.requests_started,0);assert.equal(p.reserved_microrub,0);assert.equal(p.counts.PENDING,2);});
test('B3 edge: genuine unknown cannot be changed to not-sent by stale attempt',async()=>{const j=await create();await claim(j,'a',0);await S.recover({jobId:j,owner,workerId:'new-worker',now:1001});await assert.rejects(()=>finish(j,'a',0,'not_sent'),{code:'ASYNC_STALE_ATTEMPT'});const p=await S.getSummary(j,owner);assert.equal(p.counts.UNKNOWN,1);assert.equal(p.reserved_microrub,100);});
test('B3 edge: released known-unsent reserve never removes pause',async()=>{const j=await create();await claim(j,'a',0);await S.control({jobId:j,owner,action:'pause',now:1001});await finish(j,'a',0,'not_sent');assert.equal((await claim(j,'b',0)).reason,'PAUSED');assert.equal((await S.getSummary(j,owner)).control,'PAUSED');});
test('B3 edge: immediate receipt requires raw and operation before transition',async()=>{const j=await create();await claim(j,'a',0);await assert.rejects(()=>finish(j,'a',0,'received',{operationId:'id'}),{code:'ASYNC_RAW_RESPONSE_REQUIRED'});assert.equal((await S.readItem(j,owner,0)).state,'SUBMITTING');assert.equal((await S.getSummary(j,owner)).operations_accepted,0);});
test('B3 edge: rejected submit is failed, not empty success, reserve remains conservative',async()=>{const j=await create();await claim(j,'a',0);await finish(j,'a',0,'rejected',{errorCode:'ASYNC_HTTP_401'});const p=await S.getSummary(j,owner);assert.equal(p.counts.FAILED,1);assert.equal(p.all_successful,false);assert.equal(p.reserved_microrub,100);assert.equal(await S.readResult(j,owner,0),undefined);});
test('B3 edge: exact maximum budget blocks a further pending claim',async()=>{const j=await create(2,100);await claim(j,'a',0);await finish(j,'a',0,'received',result(j+'-op'));const r=await claim(j,'b',1);assert.equal(r.reason,'BUDGET_LIMIT');assert.equal((await S.readItem(j,owner,1)).state,'PENDING');});
