import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const b6=fs.readFileSync('/mnt/data/ymb_b6/full_candidate/phase3_service_worker_bootstrap.js','utf8');
const b7=fs.readFileSync(new URL('../candidate/b7/phase3_service_worker_bootstrap.js',import.meta.url),'utf8');
const manifest=JSON.parse(fs.readFileSync('/mnt/data/ymb_b6/owner014/manifest.json','utf8'));
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
test('B7 bootstrap is exact B6 plus one deferred import block',()=>{assert.equal(sha(b6),'6bbd3d52d41d52e1f5d6c4f724dbbb9450dec2012ec99712b127a0d063a2c7b5');assert.equal(sha(b7),'40565b792b9210b5b97795bb7b9c71577a5008bb312077e06a4a54b349dd9c88');const removed=b7.replace(/  importScripts\(\n    "shared\/search_async_store\.js",\n    "shared\/search_async_protocol\.js",\n    "shared\/search_async_transport\.js",\n    "shared\/search_async_normalizer\.js",\n    "shared\/search_async_runtime\.js",\n    "search_async_worker_transport\.js"\n  \);\n/,'');assert.equal(removed,b6);});
test('deferred modules load only after shared Search guard binding',()=>{const binding=b7.indexOf('"search_admission_worker_binding.js"');const store=b7.indexOf('"shared/search_async_store.js"');const protocol=b7.indexOf('"shared/search_async_protocol.js"');const transport=b7.indexOf('"shared/search_async_transport.js"');const normalizer=b7.indexOf('"shared/search_async_normalizer.js"');const runtime=b7.indexOf('"shared/search_async_runtime.js"');const worker=b7.indexOf('"search_async_worker_transport.js"');const batch=b7.indexOf('"shared/search_batch_protocol.js"');assert.ok(binding>=0&&binding<store&&store<protocol&&protocol<transport&&transport<normalizer&&normalizer<runtime&&runtime<worker&&worker<batch);});
test('operation host permission is deliberately absent at B7',()=>{assert.equal((manifest.host_permissions||[]).includes('https://operation.api.cloud.yandex.net/*'),false);});
test('existing Search API host remains present',()=>{assert.equal((manifest.host_permissions||[]).includes('https://searchapi.api.cloud.yandex.net/*'),true);});
