import csv, json
from collections import Counter, defaultdict
from pathlib import Path

ROOT=Path(__file__).resolve().parent
ASSIGN=ROOT/'STEP_12_STRUCTURAL_UNIT_ASSIGNMENTS_V4.tsv'
HIST=ROOT/'STEP_12_PHRASE_ACTION_MAP.tsv'
SALVAGE=ROOT/'STEP_12_NO_PAGE_OUTSIDE_SALVAGE_REVIEW_V4.tsv'
OUT=ROOT/'STEP_12_SEMANTIC_CORRECTION_REVIEW_PACKET.md'
OUT_CASES=ROOT/'STEP_12_SEMANTIC_CORRECTION_REGRESSION_ACTUAL.tsv'


def read(path):
    with path.open(encoding='utf-8',newline='') as f:return list(csv.DictReader(f,delimiter='\t'))

rows=read(ASSIGN); hist=read(HIST); salvage=read(SALVAGE)
by_phrase={r['phrase']:r for r in rows}

MIXED=[
'WINDOW_INSTALLATION_DIY_INFO','PANORAMIC_WINDOWS_COMMERCIAL','GLAZING_PERMISSION_INFO','WOOD_WINDOWS_COMMERCIAL',
'WINDOW_HARDWARE_INFO','WINDOW_REPAIR_DIY_INFO','WINDOW_HARDWARE_SHOPPING','WINDOW_ACCESSORIES_SHOPPING']

REGRESSION_CASES=[
'пластиковые окна в деревянном доме','остекление открытого балкона','алюминиевые жалюзи на окна','rehau окна официальный сайт',
'пластиковые окна от производителя официальный сайт','как установить пластиковую дверь','как установить пластиковое окно','как установить алюминиевые окна',
'как сделать французское окно своими руками','открой панорамное окно','панорамные окна купить','панорамные окна на балконе','веранда с панорамными окнами',
'какие панорамные окна лучше','барбекю с панорамными окнами','оконная фурнитура roto отзывы','чем смазать оконную фурнитуру',
'оконная фурнитура виды','замена фурнитуры на пластиковых окнах цена','купить оконную фурнитуру','ремонт жалюзи на пластиковые окна',
'жалюзи на пластиковые окна','шторы на пластиковые окна','пластиковые окна в рассрочку']

case_rows=[]
for p in REGRESSION_CASES:
    r=by_phrase.get(p)
    if not r:
        case_rows.append({'phrase':p,'found':'false','final_structural_unit_id':'','final_unit_task':'','business_scope_state':'','unit_page_role':'','primary_page_candidate':'','supporting_page':'','recommendation_maturity':'','assignment_origin':'','correction_reason':''})
    else:
        case_rows.append({'phrase':p,'found':'true','final_structural_unit_id':r['final_structural_unit_id'],'final_unit_task':r['final_unit_task'],'business_scope_state':r['business_scope_state'],'unit_page_role':r['unit_page_role'],'primary_page_candidate':r['primary_page_candidate'],'supporting_page':r['supporting_page'],'recommendation_maturity':r['recommendation_maturity'],'assignment_origin':r['assignment_origin'],'correction_reason':r['correction_reason']})
with OUT_CASES.open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(case_rows[0].keys()),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(case_rows)

# Source mixed-cluster redistribution.
source_map=defaultdict(Counter)
for r in rows:
    cid=r['original_effective_cluster_id']
    if cid in MIXED: source_map[cid][r['final_structural_unit_id']]+=1

# Historical no-page/outside disposition by source cluster.
salv_map=defaultdict(Counter)
for r in salvage: salv_map[r['historical_cluster_id']][r['review_disposition']]+=1

# Historical override groups -> explicit final unit distributions.
over_map=defaultdict(Counter)
for r in rows:
    if r['historical_routing_override']=='true':
        over_map[r['historical_structural_unit_id']][r['final_structural_unit_id']]+=1

lines=['# Step 12 V4 — semantic correction review packet','',
'This packet contains **actual persisted V4 output only**. It intentionally does not assign PASS/FAIL; the semantic acceptance decision is a separate analyst review.','',
f'Rows: **{len(rows)}**; regression cases extracted: **{len(case_rows)}**.','',
'## Mixed original units → explicit V4 units','']
for cid in MIXED:
    c=source_map[cid];lines.append(f'### {cid} — {sum(c.values())} phrases')
    for uid,n in sorted(c.items(),key=lambda x:(-x[1],x[0])):lines.append(f'- `{uid}` = {n}')
    lines.append('')
lines+=['## Historical NO_STANDALONE / OUTSIDE review dispositions','']
for cid in sorted(salv_map):
    c=salv_map[cid]; lines.append(f'### {cid} — {sum(c.values())} phrases')
    for state,n in sorted(c.items()):lines.append(f'- `{state}` = {n}')
    lines.append('')
lines+=['## Historical lexical override groups → explicit V4 units','']
for uid in sorted(over_map):
    c=over_map[uid];lines.append(f'### {uid} — {sum(c.values())} phrases')
    for final,n in sorted(c.items(),key=lambda x:(-x[1],x[0])):lines.append(f'- `{final}` = {n}')
    lines.append('')
lines+=['## Regression cases','',f'Actual rows are stored in `{OUT_CASES.name}`. No expected verdict is generated by this script.','']
OUT.write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps({'rows':len(rows),'mixed_source_units':len(source_map),'salvage_source_clusters':len(salv_map),'historical_override_groups':len(over_map),'regression_cases':len(case_rows)},ensure_ascii=False))
