import csv,json
from pathlib import Path
R=Path(__file__).resolve().parent
LED=R/'STEP_12_CORRECTION_DEFECT_LEDGER.tsv';STATE=R/'STEP_12_CORRECTION_CURRENT_STATE.json';A=R/'STEP_12_STRUCTURAL_UNIT_ASSIGNMENTS_V5.tsv';OUT=R/'STEP_12_D12_27_MIXED_UNIT_PACKET.tsv';INC=R/'STEP_12_D12_27_RESIDUAL_MIXED_UNITS_2026-08-31.md'
fields=['defect_id','short_name','first_run_behavior','why_it_seemed_reasonable','why_it_is_insufficient_or_wrong','root_cause','corrective_action','verification_required','status','correction_artifact','notes']
with LED.open(encoding='utf-8',newline='') as f:rows=list(csv.DictReader(f,delimiter='\t'))
if any(r['defect_id']=='D12-27' for r in rows):raise RuntimeError('D12-27 already exists')
rows.append({'defect_id':'D12-27','short_name':'RESIDUAL_MIXED_STRUCTURAL_UNITS_EXPOSED_BY_EVIDENCE_FIRST_GAP_REVIEW','first_run_behavior':'The accepted V5 structural-unit set still contained at least two materially mixed units: FRENCH_WINDOWS_COMMERCIAL included commercial, DIY and inspiration phrasing; WINDOW_ACCESSORIES_GENERAL mixed broad accessories with hardware/component and aluminium-frame queries.','why_it_seemed_reasonable':'The earlier correction split many obvious outliers, and the remaining phrases shared strong lexical/product-family similarity with their parent topics.','why_it_is_insufficient_or_wrong':'A structural unit is supposed to represent one terminal user task/page expectation. Lexical family similarity cannot substitute for task coherence; gap diagnosis and page action become circular or misleading when different tasks remain aggregated.','root_cause':'Previous semantic acceptance relied on known regression examples and rule-based splitting but did not independently challenge every high-risk member set again after the business/freshness correction.','corrective_action':'Extract every member phrase of the affected units, reassign each to an already valid structural unit when one exists or create an explicit new/deferred unit only if necessary, then rebuild V4 actions/gap review/phrase map/pair universe and add an independent regression check that no known D12-27 phrase remains in the wrong unit.','verification_required':'All member phrases from the two affected units are explicitly reviewed; commercial French core contains no DIY/inspiration phrases; general accessories contains no hardware/aluminium-frame outliers; 2332 phrase accounting remains exact; downstream V4 independent QA passes; GitHub readback passes.','status':'OPEN','correction_artifact':'','notes':'Discovered while refusing to derive D12-21 gap type directly from the action label.'})
with LED.open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
state=json.loads(STATE.read_text(encoding='utf-8'));state['open_defects']=sorted(set(state.get('open_defects',[])+['D12-27']));state['verified_fixed_defects']=[x for x in state.get('verified_fixed_defects',[]) if x!='D12-27'];state['current_correction_item']='D12-21';state['step12_complete']=False;state['step13_blocked']=True;state['next_step_allowed']=False;state['step13_status']='BLOCKED_BY_REOPENED_STEP12';state['final_github_readback']=False;state['canonical_closure_readback_passed']=False
if 'D12-27' not in state['correction_order']:state['correction_order'].append('D12-27')
STATE.write_text(json.dumps(state,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with A.open(encoding='utf-8',newline='') as f:ass=list(csv.DictReader(f,delimiter='\t'))
target={'FRENCH_WINDOWS_COMMERCIAL','WINDOW_ACCESSORIES_GENERAL'}
out=[r for r in ass if (r.get('final_structural_unit_id') or '').strip() in target]
with OUT.open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=list(out[0].keys()),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(out)
INC.write_text('''# D12-27 — residual mixed structural units\n\nStatus: **OPEN / DISCOVERED BY THIRD-AUDIT GAP REVIEW**\n\nEvidence-first gap review proved that gap type cannot be derived from the action. While reviewing member phrases, two previously accepted structural units were found to remain materially mixed: `FRENCH_WINDOWS_COMMERCIAL` and `WINDOW_ACCESSORIES_GENERAL`.\n\nThis reopens semantic correction for these exact member rows before D12-21 can close. The complete member packet is `STEP_12_D12_27_MIXED_UNIT_PACKET.tsv`.\n\nNo Step-13 work may begin until reassignment, full 2332-row rebuild and independent readback pass.\n''',encoding='utf-8')
print(json.dumps({'registered':'D12-27','packet_rows':len(out),'by_unit':{u:sum((r.get('final_structural_unit_id') or '').strip()==u for r in out) for u in sorted(target)}},ensure_ascii=False))
